Repository manikmmalhotra/socio-backend, pull requests merged in 2021-10, with the labels that each got.

#1 Create README.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted

#2 added file to check the authentication
  api/controllers/check-auth.js
Labels: enhancement, hacktoberfest-accepted

#3 added the order.js file
  api/controllers/order.js
  api/middleware/check-auth.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#4 Added product.js
  api/controllers/products.js
Labels: bug, hacktoberfest-accepted

#5 Added user.js
  api/controllers/user.js
Labels: good first issue, hacktoberfest-accepted
